package dev.actos.resources

import dev.actos.Page
import dev.actos.Transport
import dev.actos.model.CommentDetailResponse
import dev.actos.model.CommentNodeResponse
import dev.actos.model.CommentThreadResponse
import dev.actos.model.ContentSummary
import dev.actos.model.CreateCommentRequest
import dev.actos.model.UpdateCommentRequest
import dev.actos.paginateFlow
import kotlinx.coroutines.flow.Flow
import java.util.UUID

public class CommentsResource internal constructor(
    internal val transport: Transport,
) {
    /**
     * Creates a new comment or reply on a post.
     *
     * Non-safe POST calls automatically generate and send a unique UUID [idempotencyKey]
     * by default (§2.9). Caller can pass a custom string or pass `null` to explicitly disable
     * the idempotency header.
     *
     * @param postId The ID of the post being commented on.
     * @param body The text of the comment.
     * @param parentId Optional ID of the parent comment when creating a threaded reply.
     *                 The server enforces a max depth of 32; the SDK does not pre-validate depth.
     * @param attachmentIds Optional list of upload IDs to attach to the comment.
     * @param idempotencyKey Optional unique UUID for safe retries; auto-generated by default.
     * @return [ContentSummary] representing the created comment.
     */
    public suspend fun create(
        postId: String,
        body: String,
        parentId: String? = null,
        attachmentIds: List<String>? = null,
        idempotencyKey: String? = UUID.randomUUID().toString(),
    ): ContentSummary {
        val request =
            CreateCommentRequest(
                body = body,
                parentId = parentId,
                attachmentIds = attachmentIds,
            )
        val response =
            transport.post(
                path = "/posts/$postId/comments",
                body = request.toJsonRequestBody(),
                idempotencyKey = idempotencyKey,
            )
        return response.parseJson()
    }

    /**
     * Retrieves the nested comment tree for a post.
     *
     * **CRITICAL SPECIFICATION NOTE**:
     * The comment tree endpoint does **NOT** accept a `fields` parameter. Specifying `fields`
     * would flatten or disrupt nested `replies` recursion in the comment hierarchy.
     *
     * @param postId The ID of the post.
     * @param sort Sort order (e.g. `top`, `new`, `old`).
     * @param depth Maximum tree depth to fetch in this request.
     * @param parent Specific comment ID to fetch a subtree under.
     * @param limit Pagination limit for top-level comments.
     * @param cursor Cursor for the next page of top-level comments.
     * @param bodyHtml When true, computes sanitized HTML for all comment nodes in the tree.
     * @return [Page] of [CommentNodeResponse] containing root comment nodes and their nested replies.
     */
    public suspend fun list(
        postId: String,
        sort: String? = null,
        depth: Int? = null,
        parent: String? = null,
        limit: Int? = null,
        cursor: String? = null,
        bodyHtml: Boolean = false,
    ): Page<CommentNodeResponse> {
        val queryParams =
            mapOf(
                "sort" to sort,
                "depth" to depth,
                "parent" to parent,
                "limit" to limit,
                "cursor" to cursor,
                "body_html" to if (bodyHtml) "true" else null,
            )
        val response = transport.get("/posts/$postId/comments", queryParams = queryParams)
        val parsed: CommentThreadResponse = response.parseJson()
        return Page(items = parsed.comments, nextCursor = parsed.nextCursor)
    }

    /**
     * Returns a cold [Flow] streaming top-level comment nodes across pages.
     */
    public fun stream(
        postId: String,
        sort: String? = null,
        depth: Int? = null,
        parent: String? = null,
        limit: Int? = null,
        bodyHtml: Boolean = false,
    ): Flow<CommentNodeResponse> =
        paginateFlow { cursor ->
            list(
                postId = postId,
                sort = sort,
                depth = depth,
                parent = parent,
                limit = limit,
                cursor = cursor,
                bodyHtml = bodyHtml,
            )
        }

    /**
     * Retrieves a single comment by ID along with its ancestor chain up to the root post.
     *
     * **SOFT-DELETE SEMANTICS**:
     * Soft-deleted comments do **NOT** return HTTP 410 Gone. They return HTTP 200 OK with
     * `comment.deleted = true` and `comment.body = "[silindi]"` so that replies remain anchored
     * in the thread. Check `comment.deleted == true`, rather than inspecting the body text.
     *
     * @param id The comment ID (e.g. `c_7fGh2Kd`).
     * @return [CommentDetailResponse] containing the comment and its ancestor list.
     * @throws dev.actos.NotFoundException if comment does not exist (404).
     */
    public suspend fun get(id: String): CommentDetailResponse {
        val response = transport.get("/comments/$id")
        return response.parseJson()
    }

    /**
     * Updates an existing comment's body.
     *
     * Requires authentication (`[A]`) and author permissions.
     *
     * @param id The comment ID.
     * @param body The updated comment body text.
     * @return [ContentSummary] representing the updated comment.
     */
    public suspend fun update(
        id: String,
        body: String,
    ): ContentSummary {
        val request = UpdateCommentRequest(body = body)
        val response =
            transport.patch(
                path = "/comments/$id",
                body = request.toJsonRequestBody(),
            )
        return response.parseJson()
    }

    /**
     * Soft-deletes a comment.
     *
     * Requires authentication (`[A]`) and author permissions.
     * The comment will still appear in tree queries with `deleted = true` and `body = "[silindi]"`.
     *
     * @param id The comment ID.
     */
    public suspend fun delete(id: String) {
        transport.delete("/comments/$id")
    }
}
