package dev.actos.resources

import dev.actos.Transport
import dev.actos.model.ContentSummary
import dev.actos.model.UpdatePostRequest
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import okhttp3.RequestBody.Companion.toRequestBody
import java.util.UUID

public class PostsResource internal constructor(
    internal val transport: Transport,
) {
    /**
     * Creates a new post.
     *
     * Non-safe POST calls automatically generate and send a unique UUID [idempotencyKey]
     * by default (§2.9). Callers can pass their own idempotency key, or pass `null` to
     * explicitly disable idempotency header generation.
     *
     * @param title The title of the post (mandatory, non-empty).
     * @param body The text or markdown body of the post.
     * @param tags Optional list of topic tags. Tags not yet in the system are auto-created.
     * @param attachmentIds Optional list of upload IDs from `client.uploads().upload()`.
     * @param metadata Optional arbitrary JSON metadata payload.
     * @param idempotencyKey Optional unique UUID for safe retries; auto-generated by default.
     * @return [ContentSummary] representing the created post.
     */
    public suspend fun create(
        title: String,
        body: String,
        tags: List<String> = emptyList(),
        attachmentIds: List<String>? = null,
        metadata: JsonElement? = null,
        idempotencyKey: String? = UUID.randomUUID().toString(),
    ): ContentSummary {
        val jsonMap =
            buildMap<String, JsonElement> {
                put("title", JsonPrimitive(title))
                put("body", JsonPrimitive(body))
                if (tags.isNotEmpty()) {
                    put("tags", JsonArray(tags.map { JsonPrimitive(it) }))
                }
                if (attachmentIds != null) {
                    put("attachment_ids", JsonArray(attachmentIds.map { JsonPrimitive(it) }))
                }
                if (metadata != null) {
                    put("metadata", metadata)
                }
            }
        val requestBody = JsonObject(jsonMap).toString().toRequestBody(JSON_MEDIA_TYPE)
        val response =
            transport.post(
                path = "/posts",
                body = requestBody,
                idempotencyKey = idempotencyKey,
            )
        return response.parseJson()
    }

    /**
     * Retrieves a single post by its ID.
     *
     * **HTML RENDERING NOTE (`bodyHtml`)**:
     * On single post endpoints (`GET /posts/{id}`), `bodyHtml` is always computed and returned.
     * On list endpoints, `bodyHtml` is omitted unless explicitly requested via `fields`
     * (to prevent a 25x response size expansion).
     * If `bodyFormat == "plain"`, markdown is not rendered, only HTML-escaped.
     *
     * @param id The post ID (e.g. `c_7fGh2Kd`).
     * @param fields Optional list of field names for sparse fieldset filtering.
     * @return [ContentSummary] of the requested post.
     * @throws dev.actos.NotFoundException if post does not exist (404).
     * @throws dev.actos.GoneException if post has been soft-deleted (410).
     */
    public suspend fun get(
        id: String,
        fields: List<String>? = null,
    ): ContentSummary {
        val queryParams =
            mapOf(
                "fields" to fields?.joinToString(","),
            )
        val response = transport.get("/posts/$id", queryParams = queryParams)
        return response.parseJson()
    }

    /**
     * Updates an existing post's title or body.
     *
     * Requires authentication (`[A]`) and author permissions.
     *
     * @param id The ID of the post to update.
     * @param title Optional new title.
     * @param body Optional new body content.
     * @return [ContentSummary] of the updated post.
     */
    public suspend fun update(
        id: String,
        title: String? = null,
        body: String? = null,
    ): ContentSummary {
        val request =
            UpdatePostRequest(
                title = title,
                body = body,
            )
        val response =
            transport.patch(
                path = "/posts/$id",
                body = request.toJsonRequestBody(),
            )
        return response.parseJson()
    }

    /**
     * Soft-deletes an existing post.
     *
     * Requires authentication (`[A]`) and author permissions.
     * Subsequent `get` calls on this post ID will return HTTP 410 [dev.actos.GoneException].
     *
     * @param id The ID of the post to delete.
     */
    public suspend fun delete(id: String) {
        transport.delete("/posts/$id")
    }
}
