buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath("org.openapitools:openapi-generator-gradle-plugin:7.12.0")
    }
}

import org.openapitools.generator.gradle.plugin.tasks.GenerateTask


val specFile =
    providers.provider {
        val backendSpec = rootProject.file("../actos-backend/docs/openapi.json")
        if (backendSpec.exists()) {
            backendSpec
        } else {
            rootProject.file("gradle/openapi.json")
        }
    }

val warningHeader =
    """
    // GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
    // ÜRETİLDİ — elle düzenleme

    """.trimIndent()

val modelTargetDir = rootProject.file("src/main/kotlin/dev/actos/model")

val openApiGenerateModels =
    tasks.register<GenerateTask>("openApiGenerateModels") {
        group = "openapi"
        description = "Generates Kotlin models from the OpenAPI specification"

        generatorName.set("kotlin")
        inputSpec.set(specFile.map { it.absolutePath })
        outputDir.set(layout.buildDirectory.dir("generated/openapi").map { it.asFile.absolutePath })
        packageName.set("dev.actos")
        modelPackage.set("dev.actos.model")
        globalProperties.set(
            mapOf(
                "models" to "",
                "modelDocs" to "false",
                "modelTests" to "false",
            ),
        )
        configOptions.set(
            mapOf(
                "serializationLibrary" to "kotlinx_serialization",
                "enumPropertyNaming" to "UPPERCASE",
                "explicitApi" to "true",
            ),
        )
    }

val generateModels =
    tasks.register("generateModels") {
        group = "openapi"
        description = "Generates Kotlin models and synchronizes them to src/main/kotlin/dev/actos/model"
        dependsOn(openApiGenerateModels)

        doLast {
            val generatedDir = layout.buildDirectory.dir("generated/openapi/src/main/kotlin/dev/actos/model").get().asFile
            if (!generatedDir.exists()) {
                throw GradleException("Generated directory does not exist: ${generatedDir.absolutePath}")
            }

            modelTargetDir.mkdirs()

            // Remove existing model files in destination
            modelTargetDir.listFiles()?.filter { it.extension == "kt" }?.forEach { it.delete() }

            val generatedFiles = generatedDir.listFiles()?.filter { it.extension == "kt" } ?: emptyList()
            for (file in generatedFiles) {
                val content = file.readText()
                val finalContent =
                    if (content.startsWith(warningHeader)) {
                        content
                    } else {
                        warningHeader + content
                    }
                val destFile = File(modelTargetDir, file.name)
                destFile.writeText(finalContent)
            }
            logger.lifecycle("Successfully generated and synchronized ${generatedFiles.size} models to ${modelTargetDir.path}")
        }
    }

val openApiGenerateCheck =
    tasks.register<GenerateTask>("openApiGenerateCheck") {
        group = "verification"
        description = "Generates Kotlin models into a check directory for drift verification"

        generatorName.set("kotlin")
        inputSpec.set(specFile.map { it.absolutePath })
        outputDir.set(layout.buildDirectory.dir("generated/openapi-check").map { it.asFile.absolutePath })
        packageName.set("dev.actos")
        modelPackage.set("dev.actos.model")
        globalProperties.set(
            mapOf(
                "models" to "",
                "modelDocs" to "false",
                "modelTests" to "false",
            ),
        )
        configOptions.set(
            mapOf(
                "serializationLibrary" to "kotlinx_serialization",
                "enumPropertyNaming" to "UPPERCASE",
                "explicitApi" to "true",
            ),
        )
    }

val checkGeneratedModels =
    tasks.register("checkGeneratedModels") {
        group = "verification"
        description = "Verifies that models in src/main/kotlin/dev/actos/model match openapi.json specification without drift"
        dependsOn(openApiGenerateCheck)

        doLast {
            val checkDir = layout.buildDirectory.dir("generated/openapi-check/src/main/kotlin/dev/actos/model").get().asFile
            if (!checkDir.exists()) {
                throw GradleException("Generated check directory does not exist: ${checkDir.absolutePath}")
            }

            val checkFiles = checkDir.listFiles()?.filter { it.extension == "kt" }?.associateBy { it.name } ?: emptyMap()
            val currentFiles = modelTargetDir.listFiles()?.filter { it.extension == "kt" }?.associateBy { it.name } ?: emptyMap()

            val missingInCurrent = checkFiles.keys - currentFiles.keys
            val extraInCurrent = currentFiles.keys - checkFiles.keys
            val modifiedFiles = mutableListOf<String>()

            for ((name, file) in checkFiles) {
                val currentFile = currentFiles[name] ?: continue
                val raw = file.readText()
                val expectedContent = if (raw.startsWith(warningHeader)) raw else warningHeader + raw
                val actualContent = currentFile.readText()
                if (expectedContent != actualContent) {
                    modifiedFiles.add(name)
                }
            }

            if (missingInCurrent.isNotEmpty() || extraInCurrent.isNotEmpty() || modifiedFiles.isNotEmpty()) {
                val report = buildString {
                    appendLine("Model drift detected! Generated models in src/main/kotlin/dev/actos/model do not match openapi.json.")
                    if (missingInCurrent.isNotEmpty()) {
                        appendLine("  Missing models: ${missingInCurrent.joinToString(", ")}")
                    }
                    if (extraInCurrent.isNotEmpty()) {
                        appendLine("  Extra models: ${extraInCurrent.joinToString(", ")}")
                    }
                    if (modifiedFiles.isNotEmpty()) {
                        appendLine("  Modified models: ${modifiedFiles.joinToString(", ")}")
                    }
                    appendLine("Run './gradlew generateModels' to synchronize models.")
                }
                throw GradleException(report)
            }
            logger.lifecycle("Model verification passed: ${checkFiles.size} models are up to date.")
        }
    }

tasks.named("check") {
    dependsOn(checkGeneratedModels)
}
