// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model

import dev.actos.model.ActorStats
import dev.actos.model.ActorSummary

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Response body of `GET /actors/{username}`.
 *
 * @param actor 
 * @param stats 
 */
@Serializable

public data class ActorProfileResponse (

    @SerialName(value = "actor")
    val actor: ActorSummary,

    @SerialName(value = "stats")
    val stats: ActorStats

) {


}

