// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * The outward-facing summary of an actor.  `id` is always an encoded base62 string (`a_7fGh2Kd`) — the raw `bigint` primary key never leaks into it.
 *
 * @param actorType 
 * @param createdAt RFC 3339.
 * @param id 
 * @param trustLevel Trust level (0-2), recomputed periodically by the server. There is no separate \"age\" field because account age is already derivable from `created_at`; this field carries only the computed level.
 * @param username 
 * @param avatarUrl Public URL of the avatar — `None` when no avatar has been chosen. The bucket is public-read (see [`UploadResponse::url`](crate::upload::UploadResponse)), so no signing is needed and the URL is built directly as `<public_base_url>/<object_key>`.  **It is populated only where the `ActorSummary` represents the actor's own profile** — `GET /actors/{username}`, `PATCH /actors/me`, `GET /auth/whoami`, and the follower/following/discovery/search listings. In an `ActorSummary` that summarizes the *author* of a post or comment it is always `None`: that path goes through a narrower internal record shared by many queries that know nothing about avatars, and adding the avatar there would mean touching all of them. The masked summary of a deleted author is `None` for the same reason and, additionally, **on purpose**.
 * @param bio 
 * @param displayName 
 */
@Serializable

public data class ActorSummary (

    @SerialName(value = "actor_type")
    val actorType: kotlin.String,

    /* RFC 3339. */
    @SerialName(value = "created_at")
    val createdAt: kotlin.String,

    @SerialName(value = "id")
    val id: kotlin.String,

    /* Trust level (0-2), recomputed periodically by the server. There is no separate \"age\" field because account age is already derivable from `created_at`; this field carries only the computed level. */
    @SerialName(value = "trust_level")
    val trustLevel: kotlin.Int,

    @SerialName(value = "username")
    val username: kotlin.String,

    /* Public URL of the avatar — `None` when no avatar has been chosen. The bucket is public-read (see [`UploadResponse::url`](crate::upload::UploadResponse)), so no signing is needed and the URL is built directly as `<public_base_url>/<object_key>`.  **It is populated only where the `ActorSummary` represents the actor's own profile** — `GET /actors/{username}`, `PATCH /actors/me`, `GET /auth/whoami`, and the follower/following/discovery/search listings. In an `ActorSummary` that summarizes the *author* of a post or comment it is always `None`: that path goes through a narrower internal record shared by many queries that know nothing about avatars, and adding the avatar there would mean touching all of them. The masked summary of a deleted author is `None` for the same reason and, additionally, **on purpose**. */
    @SerialName(value = "avatar_url")
    val avatarUrl: kotlin.String? = null,

    @SerialName(value = "bio")
    val bio: kotlin.String? = null,

    @SerialName(value = "display_name")
    val displayName: kotlin.String? = null

) {


}

