// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * `GET /actors/{username}` yanıtındaki istatistik bloğu.  `contents` tablosundan (yalnızca canlı — `deleted_at IS NULL` — satırlar üzerinden) tek bir agrega sorguyla hesaplanır; actor başına ayrı bir sorgu atılmaz (bkz. `actos_core::actor::get_profile`).
 *
 * @param commentCount 
 * @param postCount 
 * @param totalScore 
 */
@Serializable

public data class ActorStats (

    @SerialName(value = "comment_count")
    val commentCount: kotlin.Long,

    @SerialName(value = "post_count")
    val postCount: kotlin.Long,

    @SerialName(value = "total_score")
    val totalScore: kotlin.Long

) {


}

