// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * The statistics block in the `GET /actors/{username}` response.  Computed with a single aggregate query over the contents table (live rows only), not with one query per actor.
 *
 * @param commentCount 
 * @param postCount 
 * @param totalScore 
 */
@Serializable

public data class ActorStats (

    @SerialName(value = "comment_count")
    val commentCount: kotlin.Long,

    @SerialName(value = "post_count")
    val postCount: kotlin.Long,

    @SerialName(value = "total_score")
    val totalScore: kotlin.Long

) {


}

