// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model

import dev.actos.model.ActorSummary

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * The shared response shape of the actor-listing endpoints (`followers`, `following`, the discovery directory): one page of actors plus the cursor for the next page, if any.
 *
 * @param actors 
 * @param nextCursor `None` means this is the last page.
 */
@Serializable

public data class ActorListResponse (

    @SerialName(value = "actors")
    val actors: kotlin.collections.List<ActorSummary>,

    /* `None` means this is the last page. */
    @SerialName(value = "next_cursor")
    val nextCursor: kotlin.String? = null

) {


}

