// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Bir actor'ün dışa dönük özeti.  `id` her zaman [`actos_core::id::IdCodec`]'le kodlanmış, base62 bir string'dir (`a_7fGh2Kd`) — ham `bigint` birincil anahtarı asla buraya sızmaz.
 *
 * @param actorType 
 * @param createdAt RFC 3339.
 * @param id 
 * @param trustLevel Güven kademesi (0-2) — bkz. `actos_core::actor::recompute_trust_levels` ve `migrations/0020_trust_levels.up.sql`. Hesap yaşı zaten `created_at`'ten türetilebildiği için ayrı bir \"yaş\" alanı yok; bu alan yalnızca sunucunun periyodik olarak hesapladığı kademeyi taşıyor.
 * @param username 
 * @param avatarUrl Avatarın herkese açık URL'i — `actors.avatar_object_key` set değilse (hiç avatar seçilmemişse) `None`. Bucket public-read olduğu için (bkz. `crate::upload::UploadResponse.url`) imzalama gerekmiyor, URL doğrudan `<public_base_url>/<object_key>` biçiminde üretiliyor.  **Yalnızca actor'ün kendi profilini temsil eden dönüşümlerde (`GET /actors/{username}`, `PATCH /actors/me`, `GET /auth/whoami`, takipçi/takip/keşif/arama listeleri) dolu döner.** Bir içeriğin (post/yorum) yazarını özetleyen `ActorSummary`'lerde (bkz. `actos-api/src/routes/posts.rs`) her zaman `None`'dur — o yol `Content.author`'ın taşıdığı `ActorRecord` üzerinden geçiyor ve `ActorRecord` bilerek avatar taşımıyor (gerekçe: `actos_core::auth::AuthenticatedActor` ve `actos_core::actor::Profile` üzerindeki yorumlar — `ActorRecord`, `crate::comment`/ `crate::interaction`/`crate::feed`/`crate::search` gibi avatarı hiç bilmeyen birçok sorgu tarafından da paylaşılan, dar bir tip; avatarı oraya eklemek o modüllerin hepsinin güncellenmesini gerektirirdi). Silinmiş bir yazarın maskelenmiş özetinde de aynı sebeple ve ayrıca **kasıtlı olarak** hep `None` (bkz. `actos-api/src/routes/posts.rs::masked_actor_summary`).
 * @param bio 
 * @param displayName 
 */
@Serializable

public data class ActorSummary (

    @SerialName(value = "actor_type")
    val actorType: kotlin.String,

    /* RFC 3339. */
    @SerialName(value = "created_at")
    val createdAt: kotlin.String,

    @SerialName(value = "id")
    val id: kotlin.String,

    /* Güven kademesi (0-2) — bkz. `actos_core::actor::recompute_trust_levels` ve `migrations/0020_trust_levels.up.sql`. Hesap yaşı zaten `created_at`'ten türetilebildiği için ayrı bir \"yaş\" alanı yok; bu alan yalnızca sunucunun periyodik olarak hesapladığı kademeyi taşıyor. */
    @SerialName(value = "trust_level")
    val trustLevel: kotlin.Int,

    @SerialName(value = "username")
    val username: kotlin.String,

    /* Avatarın herkese açık URL'i — `actors.avatar_object_key` set değilse (hiç avatar seçilmemişse) `None`. Bucket public-read olduğu için (bkz. `crate::upload::UploadResponse.url`) imzalama gerekmiyor, URL doğrudan `<public_base_url>/<object_key>` biçiminde üretiliyor.  **Yalnızca actor'ün kendi profilini temsil eden dönüşümlerde (`GET /actors/{username}`, `PATCH /actors/me`, `GET /auth/whoami`, takipçi/takip/keşif/arama listeleri) dolu döner.** Bir içeriğin (post/yorum) yazarını özetleyen `ActorSummary`'lerde (bkz. `actos-api/src/routes/posts.rs`) her zaman `None`'dur — o yol `Content.author`'ın taşıdığı `ActorRecord` üzerinden geçiyor ve `ActorRecord` bilerek avatar taşımıyor (gerekçe: `actos_core::auth::AuthenticatedActor` ve `actos_core::actor::Profile` üzerindeki yorumlar — `ActorRecord`, `crate::comment`/ `crate::interaction`/`crate::feed`/`crate::search` gibi avatarı hiç bilmeyen birçok sorgu tarafından da paylaşılan, dar bir tip; avatarı oraya eklemek o modüllerin hepsinin güncellenmesini gerektirirdi). Silinmiş bir yazarın maskelenmiş özetinde de aynı sebeple ve ayrıca **kasıtlı olarak** hep `None` (bkz. `actos-api/src/routes/posts.rs::masked_actor_summary`). */
    @SerialName(value = "avatar_url")
    val avatarUrl: kotlin.String? = null,

    @SerialName(value = "bio")
    val bio: kotlin.String? = null,

    @SerialName(value = "display_name")
    val displayName: kotlin.String? = null

) {


}

