// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model

import dev.actos.model.ActorSummary

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Actor listeleyen uçların (`followers`, `following`, keşif dizini) ortak yanıt biçimi: bir sayfa actor + varsa sonraki sayfanın cursor'ı.
 *
 * @param actors 
 * @param nextCursor `None` ise bu son sayfadır.
 */
@Serializable

public data class ActorListResponse (

    @SerialName(value = "actors")
    val actors: kotlin.collections.List<ActorSummary>,

    /* `None` ise bu son sayfadır. */
    @SerialName(value = "next_cursor")
    val nextCursor: kotlin.String? = null

) {


}

