// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * An audit trail record.
 *
 * @param actionType 
 * @param adminUsername Username of the admin who performed the action — readable, rather than a raw id.
 * @param createdAt RFC 3339.
 * @param id 
 * @param targetId 
 * @param targetType 
 * @param reason 
 */
@Serializable

public data class AdminActionSummary (

    @SerialName(value = "action_type")
    val actionType: kotlin.String,

    /* Username of the admin who performed the action — readable, rather than a raw id. */
    @SerialName(value = "admin_username")
    val adminUsername: kotlin.String,

    /* RFC 3339. */
    @SerialName(value = "created_at")
    val createdAt: kotlin.String,

    @SerialName(value = "id")
    val id: kotlin.String,

    @SerialName(value = "target_id")
    val targetId: kotlin.Long,

    @SerialName(value = "target_type")
    val targetType: kotlin.String,

    @SerialName(value = "reason")
    val reason: kotlin.String? = null

) {


}

