// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model

import dev.actos.model.AdminActionSummary

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Response of `GET /admin/actions`.
 *
 * @param actions 
 * @param nextCursor `None` means this is the last page.
 */
@Serializable

public data class AdminActionListResponse (

    @SerialName(value = "actions")
    val actions: kotlin.collections.List<AdminActionSummary>,

    /* `None` means this is the last page. */
    @SerialName(value = "next_cursor")
    val nextCursor: kotlin.String? = null

) {


}

