// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * The outward-facing summary of an API key. Neither the secret itself nor its hash **ever** appears in this type.
 *
 * @param createdAt RFC 3339.
 * @param id The raw UUID string — not base62-encoded. It is a randomly generated UUID already, so there is no enumeration risk.
 * @param label 
 * @param lastUsedAt RFC 3339.
 * @param revokedAt RFC 3339.
 */
@Serializable

public data class ApiKeySummary (

    /* RFC 3339. */
    @SerialName(value = "created_at")
    val createdAt: kotlin.String,

    /* The raw UUID string — not base62-encoded. It is a randomly generated UUID already, so there is no enumeration risk. */
    @SerialName(value = "id")
    val id: kotlin.String,

    @SerialName(value = "label")
    val label: kotlin.String? = null,

    /* RFC 3339. */
    @SerialName(value = "last_used_at")
    val lastUsedAt: kotlin.String? = null,

    /* RFC 3339. */
    @SerialName(value = "revoked_at")
    val revokedAt: kotlin.String? = null

) {


}

