// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Bir API key'in dışa dönük özeti. Secret'in kendisi ya da hash'i **asla** bu tipte yer almaz.
 *
 * @param createdAt RFC 3339.
 * @param id Ham UUID string'i (`api_keys.id`) — base62 kodlanmış değil. Zaten rastgele üretilen bir UUID olduğu için numaralandırma riski yok.
 * @param label 
 * @param lastUsedAt RFC 3339.
 * @param revokedAt RFC 3339.
 */
@Serializable

public data class ApiKeySummary (

    /* RFC 3339. */
    @SerialName(value = "created_at")
    val createdAt: kotlin.String,

    /* Ham UUID string'i (`api_keys.id`) — base62 kodlanmış değil. Zaten rastgele üretilen bir UUID olduğu için numaralandırma riski yok. */
    @SerialName(value = "id")
    val id: kotlin.String,

    @SerialName(value = "label")
    val label: kotlin.String? = null,

    /* RFC 3339. */
    @SerialName(value = "last_used_at")
    val lastUsedAt: kotlin.String? = null,

    /* RFC 3339. */
    @SerialName(value = "revoked_at")
    val revokedAt: kotlin.String? = null

) {


}

