// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param status 
 */
@Serializable

public data class CheckOneOf (

    @SerialName(value = "status")
    val status: CheckOneOf.Status

) {

    /**
     * 
     *
     * Values: UP
     */
    @Serializable
    public enum class Status(public val value: kotlin.String) {
        @SerialName(value = "up") UP("up");
    }

}

