// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model

import dev.actos.model.CommentNodeResponse

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Response of `GET /posts/{id}/comments`.  `next_cursor` paginates **top-level comments only**; nested replies are not paginated. A deeper subtree is fetched separately with `?parent=<id>`.
 *
 * @param comments 
 * @param nextCursor `None` means this is the last page.
 */
@Serializable

public data class CommentThreadResponse (

    @SerialName(value = "comments")
    val comments: kotlin.collections.List<CommentNodeResponse>,

    /* `None` means this is the last page. */
    @SerialName(value = "next_cursor")
    val nextCursor: kotlin.String? = null

) {


}

