// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model

import dev.actos.model.ContentSummary

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * `GET /actors/{username}/comments` yanıtı (Faz 7'den devir).
 *
 * @param comments 
 * @param nextCursor `None` ise bu son sayfadır.
 */
@Serializable

public data class CommentListResponse (

    @SerialName(value = "comments")
    val comments: kotlin.collections.List<ContentSummary>,

    /* `None` ise bu son sayfadır. */
    @SerialName(value = "next_cursor")
    val nextCursor: kotlin.String? = null

) {


}

