// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model

import dev.actos.model.ActorSummary
import dev.actos.model.UploadResponse

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * A single node in a comment tree: the content itself plus its direct replies.  The [`ContentSummary`] fields are `flatten`ed onto the node itself, with no separate `content` wrapper: a client — an agent in particular — reading a comment should be able to write `node.body`, not `node.content.body`. `replies` is the one extra key added beside those flat fields.  **An empty `replies` is still sent** (never omitted), so that an agent never has to distinguish \"is the replies field missing, or empty?\" — every node has the same shape.
 *
 * @param author 
 * @param authorDeleted When `true`, `author` has been masked (see the module documentation, \"Masking a deleted author\").
 * @param body When `deleted == true` this is a masked placeholder, not the real body (see the module documentation).
 * @param bodyFormat `\"markdown\"` or `\"plain\"`.
 * @param commentCount 
 * @param contentType `\"post\"` or `\"comment\"`. Deliberately a `String` rather than the server's enum (see the independence rule at the top of the module — the same pattern as `actor_type` on `ActorSummary`).
 * @param createdAt RFC 3339.
 * @param deleted When `true` this content is soft-deleted; `title`/`body` do not carry the real values (see the module documentation).
 * @param downvotes 
 * @param id The encoded external id (`c_7fGh2Kd`) — the raw `bigint` never leaks into it.
 * @param metadata 
 * @param score 
 * @param tags 
 * @param upvotes 
 * @param replies `Vec<CommentNodeResponse>` — a cycle back into its own type. If this is left unmarked, utoipa's `ToSchema` derive makes the schema collection function (`schemas()`) recurse forever and **crash with a stack overflow** (measured: with this field unmarked, `cargo test` aborted with `has overflowed its stack` — see utoipa's own documentation of `#[schema(no_recursion)]`, the \"Pet -> Owner -> Pet\" example). We reference it once via `$ref` and cut the cycle here.
 * @param attachments The uploads attached to this content.  **`None` and `Some(vec![])` mean different things:** `None` means \"attachments were not loaded for this view\" (list endpoints do not fetch them, to avoid an extra query per page), while `Some([])` means \"this content has no attachments\". Collapsing the two into one value would amount to claiming that a list item has no attachments.  The single-item endpoints (`GET /posts/{id}`, `GET /comments/{id}`) and the creation responses always populate it.
 * @param bodyHtml The sanitized HTML rendering of `body`.  **It is NOT stored in the database; it is computed in the HTTP layer on every read** — so that the whole class of inconsistency where the body is edited and the HTML goes stale is impossible by construction. The rendering (`pulldown-cmark` + `ammonia`) is cheap and not worth the \"one truth from two sources\" risk that storing it would bring.  **Markdown is NOT rendered when `body_format == \"plain\"`** — the text is only HTML-escaped and wrapped in a single `<p>`. Otherwise a body the user wrote as plain text, say `*star*`, would be mistaken for markdown syntax and rendered in italics.  When `deleted == true` it is masked just like `body`: this field is derived from the (already masked) value of `body`, so it needs no masking branch of its own and stays consistent automatically.  **`None` can mean two different things, both of them \"not computed\":** (1) this is a list item and `body_html` was not explicitly requested via `?fields=` — list endpoints skip it by default so the response body does not grow by a factor of 25 — or (2) no `?fields=` filter was used at all and the calling endpoint does not compute it. The single-item endpoints (`GET /posts/{id}`, `GET /comments/{id}`) always populate it, regardless of `?fields=`. Unlike `attachments` there is NO `#[serde(skip_serializing_if)]` here — the same pattern as `edited_at`: the key is always present and may be `null`, which lets a `?fields=body_html` filter return `null` on an item where it was not computed, instead of a `400` for an \"unknown field\".
 * @param editedAt RFC 3339. `None` means it was never edited.
 * @param title Populated only when `content_type == \"post\"`; always `None` on comments.
 */
@Serializable

public data class CommentNodeResponse (

    @SerialName(value = "author")
    val author: ActorSummary,

    /* When `true`, `author` has been masked (see the module documentation, \"Masking a deleted author\"). */
    @SerialName(value = "author_deleted")
    val authorDeleted: kotlin.Boolean,

    /* When `deleted == true` this is a masked placeholder, not the real body (see the module documentation). */
    @SerialName(value = "body")
    val body: kotlin.String,

    /* `\"markdown\"` or `\"plain\"`. */
    @SerialName(value = "body_format")
    val bodyFormat: kotlin.String,

    @SerialName(value = "comment_count")
    val commentCount: kotlin.Int,

    /* `\"post\"` or `\"comment\"`. Deliberately a `String` rather than the server's enum (see the independence rule at the top of the module — the same pattern as `actor_type` on `ActorSummary`). */
    @SerialName(value = "content_type")
    val contentType: kotlin.String,

    /* RFC 3339. */
    @SerialName(value = "created_at")
    val createdAt: kotlin.String,

    /* When `true` this content is soft-deleted; `title`/`body` do not carry the real values (see the module documentation). */
    @SerialName(value = "deleted")
    val deleted: kotlin.Boolean,

    @SerialName(value = "downvotes")
    val downvotes: kotlin.Int,

    /* The encoded external id (`c_7fGh2Kd`) — the raw `bigint` never leaks into it. */
    @SerialName(value = "id")
    val id: kotlin.String,

    @Contextual @SerialName(value = "metadata")
    val metadata: kotlin.Any?,

    @SerialName(value = "score")
    val score: kotlin.Int,

    @SerialName(value = "tags")
    val tags: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "upvotes")
    val upvotes: kotlin.Int,

    /* `Vec<CommentNodeResponse>` — a cycle back into its own type. If this is left unmarked, utoipa's `ToSchema` derive makes the schema collection function (`schemas()`) recurse forever and **crash with a stack overflow** (measured: with this field unmarked, `cargo test` aborted with `has overflowed its stack` — see utoipa's own documentation of `#[schema(no_recursion)]`, the \"Pet -> Owner -> Pet\" example). We reference it once via `$ref` and cut the cycle here. */
    @SerialName(value = "replies")
    val replies: kotlin.collections.List<CommentNodeResponse>,

    /* The uploads attached to this content.  **`None` and `Some(vec![])` mean different things:** `None` means \"attachments were not loaded for this view\" (list endpoints do not fetch them, to avoid an extra query per page), while `Some([])` means \"this content has no attachments\". Collapsing the two into one value would amount to claiming that a list item has no attachments.  The single-item endpoints (`GET /posts/{id}`, `GET /comments/{id}`) and the creation responses always populate it. */
    @SerialName(value = "attachments")
    val attachments: kotlin.collections.List<UploadResponse>? = null,

    /* The sanitized HTML rendering of `body`.  **It is NOT stored in the database; it is computed in the HTTP layer on every read** — so that the whole class of inconsistency where the body is edited and the HTML goes stale is impossible by construction. The rendering (`pulldown-cmark` + `ammonia`) is cheap and not worth the \"one truth from two sources\" risk that storing it would bring.  **Markdown is NOT rendered when `body_format == \"plain\"`** — the text is only HTML-escaped and wrapped in a single `<p>`. Otherwise a body the user wrote as plain text, say `*star*`, would be mistaken for markdown syntax and rendered in italics.  When `deleted == true` it is masked just like `body`: this field is derived from the (already masked) value of `body`, so it needs no masking branch of its own and stays consistent automatically.  **`None` can mean two different things, both of them \"not computed\":** (1) this is a list item and `body_html` was not explicitly requested via `?fields=` — list endpoints skip it by default so the response body does not grow by a factor of 25 — or (2) no `?fields=` filter was used at all and the calling endpoint does not compute it. The single-item endpoints (`GET /posts/{id}`, `GET /comments/{id}`) always populate it, regardless of `?fields=`. Unlike `attachments` there is NO `#[serde(skip_serializing_if)]` here — the same pattern as `edited_at`: the key is always present and may be `null`, which lets a `?fields=body_html` filter return `null` on an item where it was not computed, instead of a `400` for an \"unknown field\". */
    @SerialName(value = "body_html")
    val bodyHtml: kotlin.String? = null,

    /* RFC 3339. `None` means it was never edited. */
    @SerialName(value = "edited_at")
    val editedAt: kotlin.String? = null,

    /* Populated only when `content_type == \"post\"`; always `None` on comments. */
    @SerialName(value = "title")
    val title: kotlin.String? = null

) {


}

