// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model

import dev.actos.model.ContentSummary

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * `GET /comments/{id}` yanıtı: yorum + kökten kendisine kadar ata zinciri.  `ancestors` kökten başlar (ilk öğe her zaman post'tur) ve yorumun kendisini **içermez** — bir breadcrumb'ın doğal sırası bu.
 *
 * @param ancestors 
 * @param comment 
 */
@Serializable

public data class CommentDetailResponse (

    @SerialName(value = "ancestors")
    val ancestors: kotlin.collections.List<ContentSummary>,

    @SerialName(value = "comment")
    val comment: ContentSummary

) {


}

