// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model

import dev.actos.model.CommentNodeResponse

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * `GET /posts/{id}/comments` yanıtı.  `next_cursor` **yalnızca üst seviye yorumları** sayfalar; iç içe yanıtlar sayfalanmaz (bkz. `actos_core::comment::list_comment_tree`). Daha derin bir alt ağaç `?parent=<id>` ile ayrıca çekilir.
 *
 * @param comments 
 * @param nextCursor `None` ise bu son sayfadır.
 */
@Serializable

public data class CommentThreadResponse (

    @SerialName(value = "comments")
    val comments: kotlin.collections.List<CommentNodeResponse>,

    /* `None` ise bu son sayfadır. */
    @SerialName(value = "next_cursor")
    val nextCursor: kotlin.String? = null

) {


}

