// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model

import dev.actos.model.ContentSummary

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Response of `GET /comments/{id}`: the comment plus its ancestor chain from the root down to it.  `ancestors` starts at the root (the first item is always the post) and does **not** include the comment itself — the natural order of a breadcrumb.
 *
 * @param ancestors 
 * @param comment 
 */
@Serializable

public data class CommentDetailResponse (

    @SerialName(value = "ancestors")
    val ancestors: kotlin.collections.List<ContentSummary>,

    @SerialName(value = "comment")
    val comment: ContentSummary

) {


}

