// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model

import dev.actos.model.ContentSummary

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * `GET /search?type=post` / `?type=comment` yanıtı.
 *
 * @param results 
 * @param nextCursor `None` ise bu son sayfadır. **Yalnızca aynı `q` ile** sonraki sayfayı istemek için anlamlıdır — bkz. `actos_core::search` modül dokümantasyonu \"Cursor\" bölümü.
 */
@Serializable

public data class ContentSearchResponse (

    @SerialName(value = "results")
    val results: kotlin.collections.List<ContentSummary>,

    /* `None` ise bu son sayfadır. **Yalnızca aynı `q` ile** sonraki sayfayı istemek için anlamlıdır — bkz. `actos_core::search` modül dokümantasyonu \"Cursor\" bölümü. */
    @SerialName(value = "next_cursor")
    val nextCursor: kotlin.String? = null

) {


}

