// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model

import dev.actos.model.ActorSummary
import dev.actos.model.UploadResponse

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Bir içeriğin (post ya da yorum) dışa dönük özeti.
 *
 * @param author 
 * @param authorDeleted `true` ise `author` maskelenmiş demektir (bkz. modül dokümantasyonu \"Silinmiş yazar maskelemesi\").
 * @param body `deleted == true` iken maskelenmiş bir yer tutucudur, gerçek gövde değildir (bkz. modül dokümantasyonu).
 * @param bodyFormat `\"markdown\"` veya `\"plain\"`.
 * @param commentCount 
 * @param contentType `\"post\"` veya `\"comment\"`. `actos_core::content::ContentType` bilerek `String` (bkz. modül başındaki `actos-core` bağımsızlığı kuralı — `ActorSummary.actor_type` ile aynı desen).
 * @param createdAt RFC 3339.
 * @param deleted `true` ise bu içerik soft-delete edilmiş; `title`/`body` gerçek değerleri taşımaz (bkz. modül dokümantasyonu).
 * @param downvotes 
 * @param id `actos_core::id::IdCodec`'le kodlanmış dış id (`c_7fGh2Kd`) — ham `bigint` asla buraya sızmaz.
 * @param metadata 
 * @param score 
 * @param tags 
 * @param upvotes 
 * @param attachments Bu içeriğe bağlı yüklemeler.  **`None` ile `Some(vec![])` farklı şeyler:** `None` \"bu görünümde ekler yüklenmedi\" demek (liste uçları ekleri getirmiyor — sayfa başına ayrı bir sorgu maliyeti taşımamak için), `Some([])` ise \"bu içeriğin eki yok\". İkisini aynı değere çökertmek, bir liste öğesinin eksiz olduğunu iddia etmek olurdu.  Tekil uçlar (`GET /posts/{id}`, `GET /comments/{id}`) ve oluşturma yanıtları her zaman dolduruyor.
 * @param bodyHtml `body`'nin sanitize edilmiş HTML'i (Faz 18.A, bkz. NOTES.md §8.3).  **Veritabanında SAKLANMIYOR, her okumada HTTP katmanında hesaplanır** (`crate-actos-api::routes::posts::render_body_html`) — gövde düzenlenip de HTML'in eski kalması sınıfı bir tutarsızlığı kökten imkânsız kılmak için. Hesaplama `actos_core::text::render_markdown` (`pulldown-cmark` + `ammonia`) üzerinden ucuz, saklamanın getirdiği \"iki kaynaktan tek gerçek\" riskine değmiyor.  **`body_format == \"plain\"` iken markdown render EDİLMEZ** — yalnızca HTML-escape edilip tek bir `<p>` ile sarılır. Aksi halde kullanıcının düz metin niyetiyle yazdığı `*yıldız*` gibi bir gövde markdown sözdizimi sanılıp italik render edilirdi.  `deleted == true` iken `body` gibi maskelenir: bu alan `body`'nin (zaten maskelenmiş) değerinden türetildiği için ayrı bir maskeleme dalına gerek yok, otomatik tutarlı.  **`None` iki farklı sebepten olabilir, ikisi de \"hesaplanmadı\" demek:** (1) bu bir liste öğesi ve `?fields=body_html` açıkça istenmedi (liste uçlarında gövde boyutu 25 katına çıkmasın diye varsayılan olarak hesaplanmıyor), ya da (2) alan hiç `?fields=`'le filtrelenmedi ama çağıran uç zaten hesaplamıyor. Tekil uçlar (`GET /posts/{id}`, `GET /comments/{id}`) `?fields=`'ten bağımsız her zaman doldurur. `attachments`'ın aksine `#[serde(skip_serializing_if)]` YOK — `edited_at` ile aynı desen: alan her zaman anahtar olarak orada, `null` olabilir; bu da `?fields=body_html` filtresinin (bkz. `actos-api::fields:: apply_fields`) hesaplanmamış bir öğede de \"bilinmeyen alan\" `400`'ü yerine `null` dönmesini sağlıyor.
 * @param editedAt RFC 3339. `None` ise hiç düzenlenmedi.
 * @param title Yalnızca `content_type == \"post\"` iken dolu; yorumlarda her zaman `None`.
 */
@Serializable

public data class ContentSummary (

    @SerialName(value = "author")
    val author: ActorSummary,

    /* `true` ise `author` maskelenmiş demektir (bkz. modül dokümantasyonu \"Silinmiş yazar maskelemesi\"). */
    @SerialName(value = "author_deleted")
    val authorDeleted: kotlin.Boolean,

    /* `deleted == true` iken maskelenmiş bir yer tutucudur, gerçek gövde değildir (bkz. modül dokümantasyonu). */
    @SerialName(value = "body")
    val body: kotlin.String,

    /* `\"markdown\"` veya `\"plain\"`. */
    @SerialName(value = "body_format")
    val bodyFormat: kotlin.String,

    @SerialName(value = "comment_count")
    val commentCount: kotlin.Int,

    /* `\"post\"` veya `\"comment\"`. `actos_core::content::ContentType` bilerek `String` (bkz. modül başındaki `actos-core` bağımsızlığı kuralı — `ActorSummary.actor_type` ile aynı desen). */
    @SerialName(value = "content_type")
    val contentType: kotlin.String,

    /* RFC 3339. */
    @SerialName(value = "created_at")
    val createdAt: kotlin.String,

    /* `true` ise bu içerik soft-delete edilmiş; `title`/`body` gerçek değerleri taşımaz (bkz. modül dokümantasyonu). */
    @SerialName(value = "deleted")
    val deleted: kotlin.Boolean,

    @SerialName(value = "downvotes")
    val downvotes: kotlin.Int,

    /* `actos_core::id::IdCodec`'le kodlanmış dış id (`c_7fGh2Kd`) — ham `bigint` asla buraya sızmaz. */
    @SerialName(value = "id")
    val id: kotlin.String,

    @Contextual @SerialName(value = "metadata")
    val metadata: kotlin.Any?,

    @SerialName(value = "score")
    val score: kotlin.Int,

    @SerialName(value = "tags")
    val tags: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "upvotes")
    val upvotes: kotlin.Int,

    /* Bu içeriğe bağlı yüklemeler.  **`None` ile `Some(vec![])` farklı şeyler:** `None` \"bu görünümde ekler yüklenmedi\" demek (liste uçları ekleri getirmiyor — sayfa başına ayrı bir sorgu maliyeti taşımamak için), `Some([])` ise \"bu içeriğin eki yok\". İkisini aynı değere çökertmek, bir liste öğesinin eksiz olduğunu iddia etmek olurdu.  Tekil uçlar (`GET /posts/{id}`, `GET /comments/{id}`) ve oluşturma yanıtları her zaman dolduruyor. */
    @SerialName(value = "attachments")
    val attachments: kotlin.collections.List<UploadResponse>? = null,

    /* `body`'nin sanitize edilmiş HTML'i (Faz 18.A, bkz. NOTES.md §8.3).  **Veritabanında SAKLANMIYOR, her okumada HTTP katmanında hesaplanır** (`crate-actos-api::routes::posts::render_body_html`) — gövde düzenlenip de HTML'in eski kalması sınıfı bir tutarsızlığı kökten imkânsız kılmak için. Hesaplama `actos_core::text::render_markdown` (`pulldown-cmark` + `ammonia`) üzerinden ucuz, saklamanın getirdiği \"iki kaynaktan tek gerçek\" riskine değmiyor.  **`body_format == \"plain\"` iken markdown render EDİLMEZ** — yalnızca HTML-escape edilip tek bir `<p>` ile sarılır. Aksi halde kullanıcının düz metin niyetiyle yazdığı `*yıldız*` gibi bir gövde markdown sözdizimi sanılıp italik render edilirdi.  `deleted == true` iken `body` gibi maskelenir: bu alan `body`'nin (zaten maskelenmiş) değerinden türetildiği için ayrı bir maskeleme dalına gerek yok, otomatik tutarlı.  **`None` iki farklı sebepten olabilir, ikisi de \"hesaplanmadı\" demek:** (1) bu bir liste öğesi ve `?fields=body_html` açıkça istenmedi (liste uçlarında gövde boyutu 25 katına çıkmasın diye varsayılan olarak hesaplanmıyor), ya da (2) alan hiç `?fields=`'le filtrelenmedi ama çağıran uç zaten hesaplamıyor. Tekil uçlar (`GET /posts/{id}`, `GET /comments/{id}`) `?fields=`'ten bağımsız her zaman doldurur. `attachments`'ın aksine `#[serde(skip_serializing_if)]` YOK — `edited_at` ile aynı desen: alan her zaman anahtar olarak orada, `null` olabilir; bu da `?fields=body_html` filtresinin (bkz. `actos-api::fields:: apply_fields`) hesaplanmamış bir öğede de \"bilinmeyen alan\" `400`'ü yerine `null` dönmesini sağlıyor. */
    @SerialName(value = "body_html")
    val bodyHtml: kotlin.String? = null,

    /* RFC 3339. `None` ise hiç düzenlenmedi. */
    @SerialName(value = "edited_at")
    val editedAt: kotlin.String? = null,

    /* Yalnızca `content_type == \"post\"` iken dolu; yorumlarda her zaman `None`. */
    @SerialName(value = "title")
    val title: kotlin.String? = null

) {


}

