// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model

import dev.actos.model.ContentSummary

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Response of `GET /search?type=post` / `?type=comment`.
 *
 * @param results 
 * @param nextCursor `None` means this is the last page. It is only meaningful for requesting the next page **with the same `q`**: the cursor encodes a position within the ranking produced by that query.
 */
@Serializable

public data class ContentSearchResponse (

    @SerialName(value = "results")
    val results: kotlin.collections.List<ContentSummary>,

    /* `None` means this is the last page. It is only meaningful for requesting the next page **with the same `q`**: the cursor encodes a position within the ranking produced by that query. */
    @SerialName(value = "next_cursor")
    val nextCursor: kotlin.String? = null

) {


}

