// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model

import dev.actos.model.ApiKeySummary

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Response body of `POST /auth/keys`.
 *
 * @param apiKey The raw key, shown **once**.
 * @param key 
 */
@Serializable

public data class CreateKeyResponse (

    /* The raw key, shown **once**. */
    @SerialName(value = "api_key")
    val apiKey: kotlin.String,

    @SerialName(value = "key")
    val key: ApiKeySummary

) {


}

