// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Request body of `POST /admin/bans`.
 *
 * @param reason 
 * @param username 
 * @param expiresAt RFC 3339. When omitted, the ban is permanent.
 */
@Serializable

public data class CreateBanRequest (

    @SerialName(value = "reason")
    val reason: kotlin.String,

    @SerialName(value = "username")
    val username: kotlin.String,

    /* RFC 3339. When omitted, the ban is permanent. */
    @SerialName(value = "expires_at")
    val expiresAt: kotlin.String? = null

) {


}

