// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Request body of `POST /posts/{id}/comments`.
 *
 * @param body 
 * @param attachmentIds Attachment ids returned by `POST /uploads`. Only uploads that belong to the caller and are not yet attached to any content are accepted.
 * @param parentId When omitted the comment becomes a direct child of the post; when given it becomes a reply to that comment. In external id form (`c_...`).
 */
@Serializable

public data class CreateCommentRequest (

    @SerialName(value = "body")
    val body: kotlin.String,

    /* Attachment ids returned by `POST /uploads`. Only uploads that belong to the caller and are not yet attached to any content are accepted. */
    @SerialName(value = "attachment_ids")
    val attachmentIds: kotlin.collections.List<kotlin.String>? = null,

    /* When omitted the comment becomes a direct child of the post; when given it becomes a reply to that comment. In external id form (`c_...`). */
    @SerialName(value = "parent_id")
    val parentId: kotlin.String? = null

) {


}

