// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * `POST /reports` isteği.
 *
 * @param reason 
 * @param targetId 
 * @param targetType `\"post\"` veya `\"comment\"`. İçeriğin gerçek türüyle uyuşmalı.
 */
@Serializable

public data class CreateReportRequest (

    @SerialName(value = "reason")
    val reason: kotlin.String,

    @SerialName(value = "target_id")
    val targetId: kotlin.String,

    /* `\"post\"` veya `\"comment\"`. İçeriğin gerçek türüyle uyuşmalı. */
    @SerialName(value = "target_type")
    val targetType: kotlin.String

) {


}

