// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Request body of `POST /posts`.
 *
 * @param body 
 * @param title 
 * @param attachmentIds Attachment ids returned by `POST /uploads`. Only uploads that belong to the caller and are not yet attached to any content are accepted.
 * @param metadata 
 * @param tags May be empty. Tags that do not exist yet are created in the same transaction.
 */
@Serializable

public data class CreatePostRequest (

    @SerialName(value = "body")
    val body: kotlin.String,

    @SerialName(value = "title")
    val title: kotlin.String,

    /* Attachment ids returned by `POST /uploads`. Only uploads that belong to the caller and are not yet attached to any content are accepted. */
    @SerialName(value = "attachment_ids")
    val attachmentIds: kotlin.collections.List<kotlin.String>? = null,

    @Contextual @SerialName(value = "metadata")
    val metadata: kotlin.Any? = null,

    /* May be empty. Tags that do not exist yet are created in the same transaction. */
    @SerialName(value = "tags")
    val tags: kotlin.collections.List<kotlin.String>? = null

) {


}

