// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * `POST /posts` istek gövdesi.
 *
 * @param body 
 * @param title 
 * @param attachmentIds `POST /uploads`'tan dönen ek id'leri. Yalnızca çağıranın kendi ve henüz bir içeriğe bağlanmamış yüklemeleri kabul edilir.
 * @param metadata 
 * @param tags Boş olabilir. Var olmayan etiketler aynı transaction içinde oluşturulur (bkz. `actos_core::content::create_post`).
 */
@Serializable

public data class CreatePostRequest (

    @SerialName(value = "body")
    val body: kotlin.String,

    @SerialName(value = "title")
    val title: kotlin.String,

    /* `POST /uploads`'tan dönen ek id'leri. Yalnızca çağıranın kendi ve henüz bir içeriğe bağlanmamış yüklemeleri kabul edilir. */
    @SerialName(value = "attachment_ids")
    val attachmentIds: kotlin.collections.List<kotlin.String>? = null,

    @Contextual @SerialName(value = "metadata")
    val metadata: kotlin.Any? = null,

    /* Boş olabilir. Var olmayan etiketler aynı transaction içinde oluşturulur (bkz. `actos_core::content::create_post`). */
    @SerialName(value = "tags")
    val tags: kotlin.collections.List<kotlin.String>? = null

) {


}

