// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model

import dev.actos.model.ApiKeySummary

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * `POST /auth/keys` yanıt gövdesi.
 *
 * @param apiKey Ham key, **bir kez** gösterilir.
 * @param key 
 */
@Serializable

public data class CreateKeyResponse (

    /* Ham key, **bir kez** gösterilir. */
    @SerialName(value = "api_key")
    val apiKey: kotlin.String,

    @SerialName(value = "key")
    val key: ApiKeySummary

) {


}

