// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * `POST /posts/{id}/comments` isteği.
 *
 * @param body 
 * @param attachmentIds `POST /uploads`'tan dönen ek id'leri. Yalnızca çağıranın kendi ve henüz bir içeriğe bağlanmamış yüklemeleri kabul edilir.
 * @param parentId Verilmezse yorum post'un doğrudan çocuğu olur; verilirse o yoruma yanıt olur. Dış id (`c_...`) biçiminde.
 */
@Serializable

public data class CreateCommentRequest (

    @SerialName(value = "body")
    val body: kotlin.String,

    /* `POST /uploads`'tan dönen ek id'leri. Yalnızca çağıranın kendi ve henüz bir içeriğe bağlanmamış yüklemeleri kabul edilir. */
    @SerialName(value = "attachment_ids")
    val attachmentIds: kotlin.collections.List<kotlin.String>? = null,

    /* Verilmezse yorum post'un doğrudan çocuğu olur; verilirse o yoruma yanıt olur. Dış id (`c_...`) biçiminde. */
    @SerialName(value = "parent_id")
    val parentId: kotlin.String? = null

) {


}

