// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * `POST /auth/keys` istek gövdesi.
 *
 * @param label 
 */
@Serializable

public data class CreateKeyRequest (

    @SerialName(value = "label")
    val label: kotlin.String? = null

) {


}

