// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Request body of `DELETE /actors/me`.  Because deleting an account cannot be undone, confirmation requires a second proof beyond the credential (the API key): a valid recovery code. The code is consumed in the process.
 *
 * @param recoveryCode 
 */
@Serializable

public data class DeleteAccountRequest (

    @SerialName(value = "recovery_code")
    val recoveryCode: kotlin.String

) {


}

