// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * `DELETE /actors/me` istek gövdesi.  Hesap silme geri alınamaz bir işlem olduğu için onay, kimlik bilgisinin (API key) yanı sıra ikinci bir kanıt — geçerli bir kurtarma kodu — gerektiriyor. Kod aynı zamanda tüketilir (bkz. `actos_core::actor::delete_account`).
 *
 * @param recoveryCode 
 */
@Serializable

public data class DeleteAccountRequest (

    @SerialName(value = "recovery_code")
    val recoveryCode: kotlin.String

) {


}

