// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Machine-readable error codes the API can return.  Carried as a string in the `code` field of the response body (`\"RATE_LIMITED\"`). This list is a contract: the meaning of an existing code is never changed, only new ones are added.
 *
 * Values: VALIDATION_FAILED,MISSING_CREDENTIALS,INVALID_KEY,FORBIDDEN,BANNED,NOT_FOUND,GONE,CONFLICT,RATE_LIMITED,UNSUPPORTED_MEDIA,INVALID_CURSOR,INTERNAL
 */
@Serializable
public enum class ErrorCode(public val value: kotlin.String) {

    @SerialName(value = "VALIDATION_FAILED")
    VALIDATION_FAILED("VALIDATION_FAILED"),

    @SerialName(value = "MISSING_CREDENTIALS")
    MISSING_CREDENTIALS("MISSING_CREDENTIALS"),

    @SerialName(value = "INVALID_KEY")
    INVALID_KEY("INVALID_KEY"),

    @SerialName(value = "FORBIDDEN")
    FORBIDDEN("FORBIDDEN"),

    @SerialName(value = "BANNED")
    BANNED("BANNED"),

    @SerialName(value = "NOT_FOUND")
    NOT_FOUND("NOT_FOUND"),

    @SerialName(value = "GONE")
    GONE("GONE"),

    @SerialName(value = "CONFLICT")
    CONFLICT("CONFLICT"),

    @SerialName(value = "RATE_LIMITED")
    RATE_LIMITED("RATE_LIMITED"),

    @SerialName(value = "UNSUPPORTED_MEDIA")
    UNSUPPORTED_MEDIA("UNSUPPORTED_MEDIA"),

    @SerialName(value = "INVALID_CURSOR")
    INVALID_CURSOR("INVALID_CURSOR"),

    @SerialName(value = "INTERNAL")
    INTERNAL("INTERNAL");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    public companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        public fun encode(data: kotlin.Any?): kotlin.String? = if (data is ErrorCode) "$data" else null

        /**
         * Returns a valid [ErrorCode] for [data], null otherwise.
         */
        public fun decode(data: kotlin.Any?): ErrorCode? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

