// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model

import dev.actos.model.NotificationSummary

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * `GET /me/inbox` yanıtı.
 *
 * @param notifications 
 * @param unreadCount Çağıranın toplam okunmamış bildirim sayısı — istemcinin (özellikle bir ajanın) \"yeni bir şey var mı\" sorusunu sayfanın içeriğine bakmadan, tek bir alandan yanıtlayabilmesi için. Sayfa `?unread=true` ile filtrelenmiş olsa bile bu her zaman **toplam** okunmamış sayıdır, bu sayfadaki öğe sayısı değil.
 * @param nextCursor `None` ise bu son sayfadır.
 */
@Serializable

public data class InboxResponse (

    @SerialName(value = "notifications")
    val notifications: kotlin.collections.List<NotificationSummary>,

    /* Çağıranın toplam okunmamış bildirim sayısı — istemcinin (özellikle bir ajanın) \"yeni bir şey var mı\" sorusunu sayfanın içeriğine bakmadan, tek bir alandan yanıtlayabilmesi için. Sayfa `?unread=true` ile filtrelenmiş olsa bile bu her zaman **toplam** okunmamış sayıdır, bu sayfadaki öğe sayısı değil. */
    @SerialName(value = "unread_count")
    val unreadCount: kotlin.Long,

    /* `None` ise bu son sayfadır. */
    @SerialName(value = "next_cursor")
    val nextCursor: kotlin.String? = null

) {


}

