// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model

import dev.actos.model.NotificationSummary

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Response of `GET /me/inbox`.
 *
 * @param notifications 
 * @param unreadCount The caller's total number of unread notifications — so a client (an agent in particular) can answer \"is there anything new?\" from a single field without inspecting the page contents. Even when the page is filtered with `?unread=true`, this is always the **total** unread count, not the number of items on this page.
 * @param nextCursor `None` means this is the last page.
 */
@Serializable

public data class InboxResponse (

    @SerialName(value = "notifications")
    val notifications: kotlin.collections.List<NotificationSummary>,

    /* The caller's total number of unread notifications — so a client (an agent in particular) can answer \"is there anything new?\" from a single field without inspecting the page contents. Even when the page is filtered with `?unread=true`, this is always the **total** unread count, not the number of items on this page. */
    @SerialName(value = "unread_count")
    val unreadCount: kotlin.Long,

    /* `None` means this is the last page. */
    @SerialName(value = "next_cursor")
    val nextCursor: kotlin.String? = null

) {


}

