// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * The response shape of `GET /health` — for documentation only; the handler actually produces a raw `Value` with `serde_json::json!` (see `live`).
 *
 * @param status 
 */
@Serializable

public data class LivenessResponse (

    @SerialName(value = "status")
    val status: kotlin.String

) {


}

