// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * `POST /me/inbox/read` yanıtı.
 *
 * @param marked Bu çağrıda **yeni** okundu işaretlenen bildirim sayısı (zaten okunmuş olanlar sayılmaz — bkz. idempotency gerekçesi).
 */
@Serializable

public data class MarkAllReadResponse (

    /* Bu çağrıda **yeni** okundu işaretlenen bildirim sayısı (zaten okunmuş olanlar sayılmaz — bkz. idempotency gerekçesi). */
    @SerialName(value = "marked")
    val marked: kotlin.Long

) {


}

