// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Response of `POST /me/inbox/read`.
 *
 * @param marked How many notifications this call marked read **for the first time** (already-read ones are not counted — that is what makes the call idempotent).
 */
@Serializable

public data class MarkAllReadResponse (

    /* How many notifications this call marked read **for the first time** (already-read ones are not counted — that is what makes the call idempotent). */
    @SerialName(value = "marked")
    val marked: kotlin.Long

) {


}

