// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * `DELETE /admin/contents/{id}` isteği.  Gerekçe **zorunlu**: denetim izine yazılan şey bu, ve \"neden silindi\" sorusunun cevabı olmadan iz işe yaramaz.
 *
 * @param reason 
 */
@Serializable

public data class ModerateDeleteRequest (

    @SerialName(value = "reason")
    val reason: kotlin.String

) {


}

