// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Request body of `DELETE /admin/contents/{id}`.  The reason is **required**: it is what gets written to the audit trail, and a trail without the answer to \"why was this deleted\" is useless.
 *
 * @param reason 
 */
@Serializable

public data class ModerateDeleteRequest (

    @SerialName(value = "reason")
    val reason: kotlin.String

) {


}

