// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model

import dev.actos.model.ActorSummary

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * The outward-facing summary of a single notification row.
 *
 * @param createdAt RFC 3339.
 * @param id 
 * @param kind One of `\"comment_on_post\"`, `\"reply_to_comment\"`, `\"new_follower\"` or `\"moderation_action\"`.
 * @param payload 
 * @param targetId The encoded external id, in the space given by `target_type` (`c_...` or `a_...`).  **The target may have been deleted since** (soft delete): the row is still returned and `target_id` is still a valid encoded id — a client that tries to fetch the target with it will get `410 Gone` from there. The notification itself is neither removed nor hidden.
 * @param targetType `\"content\"` or `\"actor\"` — determines which id space `target_id` belongs to.
 * @param actor The actor that triggered the notification. `None` only for system-originated events (no path produces one today).
 * @param readAt RFC 3339. `None` means it has not been read yet.
 */
@Serializable

public data class NotificationSummary (

    /* RFC 3339. */
    @SerialName(value = "created_at")
    val createdAt: kotlin.String,

    @SerialName(value = "id")
    val id: kotlin.String,

    /* One of `\"comment_on_post\"`, `\"reply_to_comment\"`, `\"new_follower\"` or `\"moderation_action\"`. */
    @SerialName(value = "kind")
    val kind: kotlin.String,

    @Contextual @SerialName(value = "payload")
    val payload: kotlin.Any?,

    /* The encoded external id, in the space given by `target_type` (`c_...` or `a_...`).  **The target may have been deleted since** (soft delete): the row is still returned and `target_id` is still a valid encoded id — a client that tries to fetch the target with it will get `410 Gone` from there. The notification itself is neither removed nor hidden. */
    @SerialName(value = "target_id")
    val targetId: kotlin.String,

    /* `\"content\"` or `\"actor\"` — determines which id space `target_id` belongs to. */
    @SerialName(value = "target_type")
    val targetType: kotlin.String,

    /* The actor that triggered the notification. `None` only for system-originated events (no path produces one today). */
    @SerialName(value = "actor")
    val actor: ActorSummary? = null,

    /* RFC 3339. `None` means it has not been read yet. */
    @SerialName(value = "read_at")
    val readAt: kotlin.String? = null

) {


}

