// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model

import dev.actos.model.ActorSummary

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Tek bir bildirim satırının dışa dönük özeti.
 *
 * @param createdAt RFC 3339.
 * @param id 
 * @param kind `\"comment_on_post\"`, `\"reply_to_comment\"`, `\"new_follower\"` ya da `\"moderation_action\"` (bkz. `actos_core::notification::NotificationKind`).
 * @param payload 
 * @param targetId `target_type`'a göre kodlanmış dış id (`c_...` ya da `a_...`).  **Hedef sonradan silinmiş olabilir** (soft-delete): bu satır yine de döner, `target_id` yine de geçerli bir kodlanmış id'dir — istemci bu id'yle hedefi çekmeye çalışırsa oradan `410 Gone` alır, bildirimin kendisi silinmez/gizlenmez (bkz. `migrations/0021_notifications.up.sql` tablo yorumu).
 * @param targetType `\"content\"` ya da `\"actor\"` — `target_id`'nin hangi id uzayına ait olduğunu belirler.
 * @param actor Bildirimi tetikleyen actor. `None` yalnızca sistem kaynaklı olaylarda (bugün üreten bir yol yok, bkz. `actos_core::notification` modül dokümantasyonu).
 * @param readAt RFC 3339. `None` ise henüz okunmadı.
 */
@Serializable

public data class NotificationSummary (

    /* RFC 3339. */
    @SerialName(value = "created_at")
    val createdAt: kotlin.String,

    @SerialName(value = "id")
    val id: kotlin.String,

    /* `\"comment_on_post\"`, `\"reply_to_comment\"`, `\"new_follower\"` ya da `\"moderation_action\"` (bkz. `actos_core::notification::NotificationKind`). */
    @SerialName(value = "kind")
    val kind: kotlin.String,

    @Contextual @SerialName(value = "payload")
    val payload: kotlin.Any?,

    /* `target_type`'a göre kodlanmış dış id (`c_...` ya da `a_...`).  **Hedef sonradan silinmiş olabilir** (soft-delete): bu satır yine de döner, `target_id` yine de geçerli bir kodlanmış id'dir — istemci bu id'yle hedefi çekmeye çalışırsa oradan `410 Gone` alır, bildirimin kendisi silinmez/gizlenmez (bkz. `migrations/0021_notifications.up.sql` tablo yorumu). */
    @SerialName(value = "target_id")
    val targetId: kotlin.String,

    /* `\"content\"` ya da `\"actor\"` — `target_id`'nin hangi id uzayına ait olduğunu belirler. */
    @SerialName(value = "target_type")
    val targetType: kotlin.String,

    /* Bildirimi tetikleyen actor. `None` yalnızca sistem kaynaklı olaylarda (bugün üreten bir yol yok, bkz. `actos_core::notification` modül dokümantasyonu). */
    @SerialName(value = "actor")
    val actor: ActorSummary? = null,

    /* RFC 3339. `None` ise henüz okunmadı. */
    @SerialName(value = "read_at")
    val readAt: kotlin.String? = null

) {


}

