// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model

import dev.actos.model.ContentSummary

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Response body of `GET /actors/{username}/posts`.  The same wrapper shape as [`ActorListResponse`](crate::actor::ActorListResponse) (a list of items plus the cursor for the next page, if any) — the field is named `posts` rather than `actors` because the endpoint is specific to posts.  **Field selection with `?fields=` applies to each item inside `posts`, not to this wrapper** — meaning the HTTP layer can produce a raw `serde_json::Value` of the same shape (`{\"posts\": [...], \"next_cursor\": ...}`) from filtered items without using this type at all. The type is still defined here so that SDKs can deserialize the unfiltered (complete) response into this struct.
 *
 * @param posts 
 * @param nextCursor `None` means this is the last page.
 */
@Serializable

public data class PostListResponse (

    @SerialName(value = "posts")
    val posts: kotlin.collections.List<ContentSummary>,

    /* `None` means this is the last page. */
    @SerialName(value = "next_cursor")
    val nextCursor: kotlin.String? = null

) {


}

