// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model

import dev.actos.model.ContentSummary

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * `GET /actors/{username}/posts` yanıt gövdesi.  `actos_types::actor::ActorListResponse` ile aynı sarmalayıcı şekli (öğe listesi + varsa sonraki sayfanın cursor'ı) — burada alan adı `posts` (`actors` değil), çünkü uç özellikle post'lara özgü.  **`?fields=` ile alan seçimi bu sarmalayıcıya değil, `posts` içindeki her öğeye uygulanır** (bkz. `actos-api/src/fields.rs` modül dokümantasyonu) — yani HTTP katmanı bu tipi hiç kullanmadan, filtrelenmiş öğelerle aynı şekle (`{\"posts\": [...], \"next_cursor\": ...}`) sahip ham bir `serde_json::Value` üretebilir. Tip yine de burada tanımlı: SDK'lar filtresiz (tam) yanıtı bu struct'a deserialize edebilsin diye.
 *
 * @param posts 
 * @param nextCursor `None` ise bu son sayfadır.
 */
@Serializable

public data class PostListResponse (

    @SerialName(value = "posts")
    val posts: kotlin.collections.List<ContentSummary>,

    /* `None` ise bu son sayfadır. */
    @SerialName(value = "next_cursor")
    val nextCursor: kotlin.String? = null

) {


}

