// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model

import dev.actos.model.ErrorCode

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * RFC 9457 \"problem details\" gövdesi.  `pub(crate)` (özel değil): Faz 16'nın OpenAPI şeması bu tipi tek bir bileşen (`components.schemas.ProblemDetails`) olarak her hata yanıtında referans veriyor (bkz. `crate::openapi` modülü) — bunun için diğer `routes/_*.rs` dosyalarından görünür olması gerekiyor.
 *
 * @param code Makine-okunur kod — istemciler `title` metnine değil buna bakmalı.
 * @param status HTTP durum kodu (gövdede de bulunması RFC'nin önerisi).
 * @param title Kısa, insan-okunur özet.
 * @param type Hata tipini tanımlayan URI (dokümantasyona işaret eder).
 * @param detail Bu spesifik oluşuma dair açıklama. İç hatalarda yok.
 * @param requestId Destek/hata ayıklama için istek kimliği.
 */
@Serializable

public data class ProblemDetails (

    /* Makine-okunur kod — istemciler `title` metnine değil buna bakmalı. */
    @Contextual @SerialName(value = "code")
    val code: ErrorCode,

    /* HTTP durum kodu (gövdede de bulunması RFC'nin önerisi). */
    @SerialName(value = "status")
    val status: kotlin.Int,

    /* Kısa, insan-okunur özet. */
    @SerialName(value = "title")
    val title: kotlin.String,

    /* Hata tipini tanımlayan URI (dokümantasyona işaret eder). */
    @SerialName(value = "type")
    val type: kotlin.String,

    /* Bu spesifik oluşuma dair açıklama. İç hatalarda yok. */
    @SerialName(value = "detail")
    val detail: kotlin.String? = null,

    /* Destek/hata ayıklama için istek kimliği. */
    @SerialName(value = "request_id")
    val requestId: kotlin.String? = null

) {


}

