// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model

import dev.actos.model.ErrorCode

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * An RFC 9457 \"problem details\" body.  `pub(crate)` rather than private: the OpenAPI schema references this type as a single component (`components.schemas.ProblemDetails`) from every error response, so it has to be visible from the other `routes/_*.rs` files.
 *
 * @param code The machine-readable code — clients should branch on this, not on the `title` text.
 * @param status The HTTP status code (the RFC recommends repeating it in the body).
 * @param title A short, human-readable summary.
 * @param type URI identifying the error type (it points at the documentation).
 * @param detail An explanation of this specific occurrence. Absent on internal errors.
 * @param requestId Request id, for support and debugging.
 */
@Serializable

public data class ProblemDetails (

    /* The machine-readable code — clients should branch on this, not on the `title` text. */
    @Contextual @SerialName(value = "code")
    val code: ErrorCode,

    /* The HTTP status code (the RFC recommends repeating it in the body). */
    @SerialName(value = "status")
    val status: kotlin.Int,

    /* A short, human-readable summary. */
    @SerialName(value = "title")
    val title: kotlin.String,

    /* URI identifying the error type (it points at the documentation). */
    @SerialName(value = "type")
    val type: kotlin.String,

    /* An explanation of this specific occurrence. Absent on internal errors. */
    @SerialName(value = "detail")
    val detail: kotlin.String? = null,

    /* Request id, for support and debugging. */
    @SerialName(value = "request_id")
    val requestId: kotlin.String? = null

) {


}

