// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model

import dev.actos.model.Check

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param database 
 * @param redis 
 * @param status 
 * @param storage 
 */
@Serializable

public data class Readiness (

    @SerialName(value = "database")
    val database: Check,

    @SerialName(value = "redis")
    val redis: Check,

    @SerialName(value = "status")
    val status: kotlin.String,

    @SerialName(value = "storage")
    val storage: Check

) {


}

