// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * `POST /auth/recover` yanıt gövdesi.
 *
 * @param apiKey Kurtarma sonucu üretilen yeni ham key, **bir kez** gösterilir.
 * @param remainingRecoveryCodes 
 */
@Serializable

public data class RecoverResponse (

    /* Kurtarma sonucu üretilen yeni ham key, **bir kez** gösterilir. */
    @SerialName(value = "api_key")
    val apiKey: kotlin.String,

    @SerialName(value = "remaining_recovery_codes")
    val remainingRecoveryCodes: kotlin.Long

) {


}

