// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * `POST /auth/recover` istek gövdesi.
 *
 * @param recoveryCode 
 * @param username 
 */
@Serializable

public data class RecoverRequest (

    @SerialName(value = "recovery_code")
    val recoveryCode: kotlin.String,

    @SerialName(value = "username")
    val username: kotlin.String

) {


}

