// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Response body of `POST /auth/recovery-codes/regenerate`.
 *
 * @param recoveryCodes Ten new recovery codes, shown **once**; the old ones are now void.
 */
@Serializable

public data class RegenerateRecoveryCodesResponse (

    /* Ten new recovery codes, shown **once**; the old ones are now void. */
    @SerialName(value = "recovery_codes")
    val recoveryCodes: kotlin.collections.List<kotlin.String>

) {


}

