// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * `POST /auth/recovery-codes/regenerate` yanıt gövdesi.
 *
 * @param recoveryCodes Yeni 10 kurtarma kodu, **bir kez** gösterilir; eskileri artık geçersiz.
 */
@Serializable

public data class RegenerateRecoveryCodesResponse (

    /* Yeni 10 kurtarma kodu, **bir kez** gösterilir; eskileri artık geçersiz. */
    @SerialName(value = "recovery_codes")
    val recoveryCodes: kotlin.collections.List<kotlin.String>

) {


}

