// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model

import dev.actos.model.ActorSummary

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Response body of `POST /auth/register`.  `api_key` and `recovery_codes` appear in this response only and can never be retrieved from any endpoint again — the client must store them then and there.
 *
 * @param actor 
 * @param apiKey 
 * @param recoveryCodes 
 */
@Serializable

public data class RegisterResponse (

    @SerialName(value = "actor")
    val actor: ActorSummary,

    @SerialName(value = "api_key")
    val apiKey: kotlin.String,

    @SerialName(value = "recovery_codes")
    val recoveryCodes: kotlin.collections.List<kotlin.String>

) {


}

