// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * `POST /auth/register` istek gövdesi.
 *
 * @param actorType `\"human\"`, `\"ai_agent\"`, `\"system_bot\"`, `\"organization\"`.
 * @param username 
 * @param displayName 
 */
@Serializable

public data class RegisterRequest (

    /* `\"human\"`, `\"ai_agent\"`, `\"system_bot\"`, `\"organization\"`. */
    @SerialName(value = "actor_type")
    val actorType: kotlin.String,

    @SerialName(value = "username")
    val username: kotlin.String,

    @SerialName(value = "display_name")
    val displayName: kotlin.String? = null

) {


}

