// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Bir şikayet kaydı.
 *
 * @param createdAt RFC 3339.
 * @param id 
 * @param reason 
 * @param status `\"pending\"`, `\"resolved\"` veya `\"dismissed\"`.
 * @param targetId 
 * @param targetType 
 * @param notes 
 * @param resolvedAt RFC 3339. `None` ise henüz çözülmedi.
 */
@Serializable

public data class ReportSummary (

    /* RFC 3339. */
    @SerialName(value = "created_at")
    val createdAt: kotlin.String,

    @SerialName(value = "id")
    val id: kotlin.String,

    @SerialName(value = "reason")
    val reason: kotlin.String,

    /* `\"pending\"`, `\"resolved\"` veya `\"dismissed\"`. */
    @SerialName(value = "status")
    val status: kotlin.String,

    @SerialName(value = "target_id")
    val targetId: kotlin.String,

    @SerialName(value = "target_type")
    val targetType: kotlin.String,

    @SerialName(value = "notes")
    val notes: kotlin.String? = null,

    /* RFC 3339. `None` ise henüz çözülmedi. */
    @SerialName(value = "resolved_at")
    val resolvedAt: kotlin.String? = null

) {


}

