// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model

import dev.actos.model.ContentSummary

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * `GET /me/saves` yanıtı.  **En son kaydedilen önce** — içeriğin yazılma zamanına göre değil. Post ve yorum bir arada olabilir (`content_type` alanı ayırt eder).
 *
 * @param saves 
 * @param nextCursor `None` ise bu son sayfadır.
 */
@Serializable

public data class SaveListResponse (

    @SerialName(value = "saves")
    val saves: kotlin.collections.List<ContentSummary>,

    /* `None` ise bu son sayfadır. */
    @SerialName(value = "next_cursor")
    val nextCursor: kotlin.String? = null

) {


}

