// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Request body of `POST /admin/roles`.
 *
 * @param username 
 * @param role One of `\"admin\"`, `\"moderator\"`, or `null` to remove the role.
 */
@Serializable

public data class SetRoleRequest (

    @SerialName(value = "username")
    val username: kotlin.String,

    /* One of `\"admin\"`, `\"moderator\"`, or `null` to remove the role. */
    @SerialName(value = "role")
    val role: kotlin.String? = null

) {


}

