// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * `POST /admin/roles` isteği.
 *
 * @param username 
 * @param role `\"admin\"`, `\"moderator\"` ya da `null` (rolü kaldır).
 */
@Serializable

public data class SetRoleRequest (

    @SerialName(value = "username")
    val username: kotlin.String,

    /* `\"admin\"`, `\"moderator\"` ya da `null` (rolü kaldır). */
    @SerialName(value = "role")
    val role: kotlin.String? = null

) {


}

