// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model

import dev.actos.model.TagSummary

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * `GET /tags` yanıtı: popülerliğe göre sıralı, cursor'lu.
 *
 * @param tags 
 * @param nextCursor `None` ise bu son sayfadır.
 */
@Serializable

public data class TagListResponse (

    @SerialName(value = "tags")
    val tags: kotlin.collections.List<TagSummary>,

    /* `None` ise bu son sayfadır. */
    @SerialName(value = "next_cursor")
    val nextCursor: kotlin.String? = null

) {


}

