// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * A single match in the `GET /tags/search` response.  There is **no** `post_count`: the autocomplete query does not count posts per tag on every keystroke, and sending an uncomputed number as `0` would carry a wrong value as if it were right.
 *
 * @param name 
 */
@Serializable

public data class TagMatch (

    @SerialName(value = "name")
    val name: kotlin.String

) {


}

