// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * `GET /tags/search` yanıtındaki tek eşleşme.  `post_count` **yok**: otomatik tamamlama sorgusu her tuş vuruşunda etiket başına post saymıyor (bkz. `actos_core::tag::TagMatch`), ve hesaplanmamış bir sayıyı `0` olarak göndermek yanlış bir değeri doğruymuş gibi taşımak olurdu.
 *
 * @param name 
 */
@Serializable

public data class TagMatch (

    @SerialName(value = "name")
    val name: kotlin.String

) {


}

