// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * A single tag in the `GET /tags` listing.
 *
 * @param createdAt RFC 3339.
 * @param name 
 * @param postCount Number of **live** posts carrying this tag (deleted ones excluded).
 */
@Serializable

public data class TagSummary (

    /* RFC 3339. */
    @SerialName(value = "created_at")
    val createdAt: kotlin.String,

    @SerialName(value = "name")
    val name: kotlin.String,

    /* Number of **live** posts carrying this tag (deleted ones excluded). */
    @SerialName(value = "post_count")
    val postCount: kotlin.Int

) {


}

