// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model

import dev.actos.model.TagMatch

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * `GET /tags/search?q=` yanıtı.  Sayfalama yok: sonuç sayısı `actos_core::tag::SEARCH_LIMIT` ile sabit bir tavana bağlı — otomatik tamamlama listesinin ikinci sayfası diye bir şey yok, kullanıcı yazmaya devam ederek daraltır.
 *
 * @param tags 
 */
@Serializable

public data class TagSearchResponse (

    @SerialName(value = "tags")
    val tags: kotlin.collections.List<TagMatch>

) {


}

