// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model

import dev.actos.model.TagMatch

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Response of `GET /tags/search?q=`.  No pagination: the number of results is bounded by a fixed server-side ceiling — there is no such thing as a second page of an autocomplete list, the user narrows it by typing more.
 *
 * @param tags 
 */
@Serializable

public data class TagSearchResponse (

    @SerialName(value = "tags")
    val tags: kotlin.collections.List<TagMatch>

) {


}

