// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * `PATCH /actors/me` istek gövdesi.  **`Option<Option<T>>` kalıbı — kısmi güncelleme:** alan JSON'da hiç yoksa dış `Option` `None` kalır (\"dokunma\"); alan açıkça `null` olarak gönderilmişse dış `Option` `Some(None)` olur (\"temizle\"); bir değer gönderilmişse `Some(Some(v))` olur (\"güncelle\"). Sıradan `#[serde(default)]` + `Option<T>` bu üç durumu ayırt edemez — `null` ile \"alan hiç gönderilmedi\" aynı `None`'a çökerdi, istemci bir alanı temizleyemezdi.  [`double_option`] bunu şöyle sağlıyor: `#[serde(default)]` sayesinde alan JSON'da hiç yoksa `deserialize_with` fonksiyonu **hiç çağrılmaz**, alan `Default::default()` (yani `None`) kalır. Alan varsa (değeri `null` da olsa) fonksiyon çağrılır ve içteki `Option<T>::deserialize` zaten `null` → `None`, değer → `Some(value)` ayrımını doğru yapar; biz bunu bir `Some(...)` ile sarmalayıp dış katmanı ekliyoruz.
 *
 * @param avatar Yeni avatar olarak kullanılacak yüklemenin **dış** id'si (`f_...` — `POST /uploads`'un döndürdüğü `id`). `display_name`/`bio` ile aynı `Option<Option<T>>` deseni: alan hiç gönderilmezse avatara dokunulmaz, `null` gönderilirse avatar kaldırılır (`actors.avatar_object_key` `NULL` olur), bir id gönderilirse o yükleme avatar yapılır.  Sunucu bu id'yi kabul etmeden önce üç şeyi doğrular (bkz. `actos_core::attachment::resolve_as_avatar`): yükleme var mı (`404`), **çağıran actor'e mi ait** (`403`), ve henüz bir içeriğe **bağlanmamış mı** (`409` — bir posta/yoruma zaten iliştirilmiş bir dosya avatar olarak yeniden kullanılamaz, iki farklı yaşam döngüsü aynı satırda çakışırdı).
 * @param bio 
 * @param displayName 
 */
@Serializable

public data class UpdateProfileRequest (

    /* Yeni avatar olarak kullanılacak yüklemenin **dış** id'si (`f_...` — `POST /uploads`'un döndürdüğü `id`). `display_name`/`bio` ile aynı `Option<Option<T>>` deseni: alan hiç gönderilmezse avatara dokunulmaz, `null` gönderilirse avatar kaldırılır (`actors.avatar_object_key` `NULL` olur), bir id gönderilirse o yükleme avatar yapılır.  Sunucu bu id'yi kabul etmeden önce üç şeyi doğrular (bkz. `actos_core::attachment::resolve_as_avatar`): yükleme var mı (`404`), **çağıran actor'e mi ait** (`403`), ve henüz bir içeriğe **bağlanmamış mı** (`409` — bir posta/yoruma zaten iliştirilmiş bir dosya avatar olarak yeniden kullanılamaz, iki farklı yaşam döngüsü aynı satırda çakışırdı). */
    @SerialName(value = "avatar")
    val avatar: kotlin.String? = null,

    @SerialName(value = "bio")
    val bio: kotlin.String? = null,

    @SerialName(value = "display_name")
    val displayName: kotlin.String? = null

) {


}

