// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Request body of `PATCH /comments/{id}`.  Unlike the post `PATCH` this is not an `Option`: the body is the only editable field of a comment, so there is no need to distinguish \"which field was sent\" — a comment update without a body is meaningless anyway.
 *
 * @param body 
 */
@Serializable

public data class UpdateCommentRequest (

    @SerialName(value = "body")
    val body: kotlin.String

) {


}

