// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Request body of `PATCH /posts/{id}`.  Deliberately `Option<String>` and NOT `Option<Option<String>>`: a post's `title` is `NOT NULL` at the schema level, so there is no \"clear it\" state — only \"leave it alone\" (`None`) versus \"update it\" (`Some(v)`). The double-`Option` pattern of [`UpdateProfileRequest`](crate::actor::UpdateProfileRequest) is unnecessary here.
 *
 * @param body 
 * @param title 
 */
@Serializable

public data class UpdatePostRequest (

    @SerialName(value = "body")
    val body: kotlin.String? = null,

    @SerialName(value = "title")
    val title: kotlin.String? = null

) {


}

