// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * `PATCH /comments/{id}` isteği.  Post'un `PATCH`'inin aksine `Option` değil: yorumların düzenlenebilecek tek alanı gövde, dolayısıyla \"hangi alan gönderildi\" ayrımına gerek yok — gövdesiz bir yorum güncellemesi zaten anlamsız.
 *
 * @param body 
 */
@Serializable

public data class UpdateCommentRequest (

    @SerialName(value = "body")
    val body: kotlin.String

) {


}

