// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Request body of `PATCH /admin/reports/{id}`.
 *
 * @param status 
 * @param notes 
 */
@Serializable

public data class UpdateReportRequest (

    @SerialName(value = "status")
    val status: kotlin.String,

    @SerialName(value = "notes")
    val notes: kotlin.String? = null

) {


}

