// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * `PATCH /posts/{id}` istek gövdesi.  Kasıtlı olarak `Option<String>` — `Option<Option<String>>` DEĞİL: bir post'un `title`'ı şema seviyesinde `NOT NULL` (bkz. `migrations/0005_contents.up.sql` → `ck_contents_shape`), yani \"temizle\" diye bir durum yok, yalnızca \"dokunma\" (`None`) / \"güncelle\" (`Some(v)`) ayrımı var. `actos_types::actor::UpdateProfileRequest`'in çift-`Option` kalıbı burada gereksiz.
 *
 * @param body 
 * @param title 
 */
@Serializable

public data class UpdatePostRequest (

    @SerialName(value = "body")
    val body: kotlin.String? = null,

    @SerialName(value = "title")
    val title: kotlin.String? = null

) {


}

