// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Request body of `PATCH /actors/me`.  **The `Option<Option<T>>` pattern — partial update:** if the field is absent from the JSON the outer `Option` stays `None` (\"leave it alone\"); if it is sent explicitly as `null` the outer `Option` becomes `Some(None)` (\"clear it\"); if a value is sent it becomes `Some(Some(v))` (\"update it\"). A plain `#[serde(default)]` + `Option<T>` cannot tell these three apart — `null` and \"field not sent at all\" would collapse into the same `None`, and a client could never clear a field.  `double_option` achieves this as follows: thanks to `#[serde(default)]`, when the field is absent from the JSON the `deserialize_with` function is **never called** and the field stays `Default::default()` (that is, `None`). When the field is present — even with a `null` value — the function is called, and the inner `Option<T>::deserialize` already draws the right distinction (`null` → `None`, a value → `Some(value)`); we wrap that in a `Some(...)` to add the outer layer.
 *
 * @param avatar The **external** id of the upload to use as the new avatar (`f_...` — the `id` returned by `POST /uploads`). Same `Option<Option<T>>` pattern as `display_name`/`bio`: if the field is absent the avatar is left alone, if `null` is sent the avatar is removed, and if an id is sent that upload becomes the avatar.  Before accepting the id the server checks three things: that the upload exists (`404`), that it **belongs to the calling actor** (`403`), and that it is **not yet attached** to any content (`409` — a file already attached to a post or comment cannot be reused as an avatar, since two different lifecycles would collide on one row).
 * @param bio 
 * @param displayName 
 */
@Serializable

public data class UpdateProfileRequest (

    /* The **external** id of the upload to use as the new avatar (`f_...` — the `id` returned by `POST /uploads`). Same `Option<Option<T>>` pattern as `display_name`/`bio`: if the field is absent the avatar is left alone, if `null` is sent the avatar is removed, and if an id is sent that upload becomes the avatar.  Before accepting the id the server checks three things: that the upload exists (`404`), that it **belongs to the calling actor** (`403`), and that it is **not yet attached** to any content (`409` — a file already attached to a post or comment cannot be reused as an avatar, since two different lifecycles would collide on one row). */
    @SerialName(value = "avatar")
    val avatar: kotlin.String? = null,

    @SerialName(value = "bio")
    val bio: kotlin.String? = null,

    @SerialName(value = "display_name")
    val displayName: kotlin.String? = null

) {


}

