// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * `POST /uploads` yanıtı ve bir içeriğin eklerinin gösterimi.  `url` ve `thumbnail_url` **doğrudan kullanılabilir**: bucket public-read olduğu için imzalama ya da ikinci bir çağrı gerekmiyor (bkz. PLAN.md Faz 13 — ileride private + presigned URL'ye geçilebilir, o zaman bu alanların anlamı değil yalnızca ömrü değişir).
 *
 * @param byteSize 
 * @param checksumSha256 Saklanan (normalize edilmiş) dosyanın SHA-256'sı, hex.
 * @param createdAt RFC 3339.
 * @param id 
 * @param mimeType Normalize sonrası her zaman `image/webp`.
 * @param thumbnailUrl 
 * @param url 
 * @param height 
 * @param width 
 */
@Serializable

public data class UploadResponse (

    @SerialName(value = "byte_size")
    val byteSize: kotlin.Long,

    /* Saklanan (normalize edilmiş) dosyanın SHA-256'sı, hex. */
    @SerialName(value = "checksum_sha256")
    val checksumSha256: kotlin.String,

    /* RFC 3339. */
    @SerialName(value = "created_at")
    val createdAt: kotlin.String,

    @SerialName(value = "id")
    val id: kotlin.String,

    /* Normalize sonrası her zaman `image/webp`. */
    @SerialName(value = "mime_type")
    val mimeType: kotlin.String,

    @SerialName(value = "thumbnail_url")
    val thumbnailUrl: kotlin.String,

    @SerialName(value = "url")
    val url: kotlin.String,

    @SerialName(value = "height")
    val height: kotlin.Int? = null,

    @SerialName(value = "width")
    val width: kotlin.Int? = null

) {


}

