// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Response of `POST /uploads`, and how a content's attachments are shown.  `url` and `thumbnail_url` are **directly usable**: the bucket is public-read, so neither signing nor a second call is needed (see PLAN.md phase 13 — a move to private + presigned URLs is possible later, and it would change only the lifetime of these fields, not their meaning).
 *
 * @param byteSize 
 * @param checksumSha256 SHA-256 of the stored (normalized) file, hex-encoded.
 * @param createdAt RFC 3339.
 * @param id 
 * @param mimeType Always `image/webp` after normalization.
 * @param thumbnailUrl 
 * @param url 
 * @param height 
 * @param width 
 */
@Serializable

public data class UploadResponse (

    @SerialName(value = "byte_size")
    val byteSize: kotlin.Long,

    /* SHA-256 of the stored (normalized) file, hex-encoded. */
    @SerialName(value = "checksum_sha256")
    val checksumSha256: kotlin.String,

    /* RFC 3339. */
    @SerialName(value = "created_at")
    val createdAt: kotlin.String,

    @SerialName(value = "id")
    val id: kotlin.String,

    /* Always `image/webp` after normalization. */
    @SerialName(value = "mime_type")
    val mimeType: kotlin.String,

    @SerialName(value = "thumbnail_url")
    val thumbnailUrl: kotlin.String,

    @SerialName(value = "url")
    val url: kotlin.String,

    @SerialName(value = "height")
    val height: kotlin.Int? = null,

    @SerialName(value = "width")
    val width: kotlin.Int? = null

) {


}

