// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param apiVersion Lets the client know which API version it is talking to.
 * @param gitSha 
 * @param name 
 * @param version 
 */
@Serializable

public data class Version (

    /* Lets the client know which API version it is talking to. */
    @SerialName(value = "api_version")
    val apiVersion: kotlin.String,

    @SerialName(value = "git_sha")
    val gitSha: kotlin.String,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "version")
    val version: kotlin.String

) {


}

