// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Response of `PUT /contents/{id}/vote`: the content's counters afterwards.  The counters come back in the response so a client does not need a extra `GET` just to see the new score after voting — that is the typical flow for agents.
 *
 * @param downvotes 
 * @param score 
 * @param upvotes 
 * @param `value` The caller's current vote on this content (`0` = no vote).
 */
@Serializable

public data class VoteResponse (

    @SerialName(value = "downvotes")
    val downvotes: kotlin.Int,

    @SerialName(value = "score")
    val score: kotlin.Int,

    @SerialName(value = "upvotes")
    val upvotes: kotlin.Int,

    /* The caller's current vote on this content (`0` = no vote). */
    @SerialName(value = "value")
    val `value`: kotlin.Int

) {


}

