// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * `PUT /contents/{id}/vote` yanıtı: işlem sonrası içeriğin sayaçları.  Sayaçlar yanıtta dönüyor ki istemci oy verdikten sonra yeni skoru görmek için ayrıca `GET` atmasın — ajanlar için tipik akış bu.
 *
 * @param downvotes 
 * @param score 
 * @param upvotes 
 * @param `value` Çağıranın bu içerikteki güncel oyu (`0` = oy yok).
 */
@Serializable

public data class VoteResponse (

    @SerialName(value = "downvotes")
    val downvotes: kotlin.Int,

    @SerialName(value = "score")
    val score: kotlin.Int,

    @SerialName(value = "upvotes")
    val upvotes: kotlin.Int,

    /* Çağıranın bu içerikteki güncel oyu (`0` = oy yok). */
    @SerialName(value = "value")
    val `value`: kotlin.Int

) {


}

