// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Request body of `PUT /contents/{id}/vote`.
 *
 * @param `value` `1` (up), `-1` (down) or `0` (retract the vote).
 */
@Serializable

public data class VoteRequest (

    /* `1` (up), `-1` (down) or `0` (retract the vote). */
    @SerialName(value = "value")
    val `value`: kotlin.Int

) {


}

