// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Response of `GET /me/votes?content_ids=...`.  The key is the external content id, the value is the vote. **Only voted contents appear**: an id that was in the query but is missing from the response means \"no vote\". Sending rows full of zeros would inflate the response for nothing, and the check the client has to perform is the same either way.
 *
 * @param votes 
 */
@Serializable

public data class VoteMapResponse (

    @SerialName(value = "votes")
    val votes: kotlin.collections.Map<kotlin.String, kotlin.Int>

) {


}

