// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * `GET /me/votes?content_ids=...` yanıtı.  Anahtar dış içerik id'si, değer oy. **Yalnızca oy verilmiş içerikler var**: sorguda geçip yanıtta olmayan bir id \"oy yok\" demek. Sıfır dolu satırlar göndermek yanıtı boşuna şişirirdi ve istemcinin yapması gereken kontrol iki durumda da aynı.
 *
 * @param votes 
 */
@Serializable

public data class VoteMapResponse (

    @SerialName(value = "votes")
    val votes: kotlin.collections.Map<kotlin.String, kotlin.Int>

) {


}

