// GENERATED BY OPENAPI-GENERATOR — DO NOT EDIT MANUALLY
// ÜRETİLDİ — elle düzenleme
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.actos.model

import dev.actos.model.ActorSummary
import dev.actos.model.ApiKeySummary

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Response body of `GET /auth/whoami`.
 *
 * @param actor 
 * @param key Summary of the key that authenticated this request.
 * @param roles `\"admin\"`, `\"moderator\"` — empty for most actors.
 */
@Serializable

public data class WhoamiResponse (

    @SerialName(value = "actor")
    val actor: ActorSummary,

    /* Summary of the key that authenticated this request. */
    @SerialName(value = "key")
    val key: ApiKeySummary,

    /* `\"admin\"`, `\"moderator\"` — empty for most actors. */
    @SerialName(value = "roles")
    val roles: kotlin.collections.List<kotlin.String>

) {


}

